import { describe, it, expect } from 'vitest';
import { initCombatV3, validateEnergyBudget, resolveRoundV3, attemptFleeV3 } from '../engine/combatV3Engine.js';
import { generateNpcCombatStats } from '../engine/npcCombatStats.js';
import type { CombatModule } from '@void-sector/shared';

const mockModules: CombatModule[] = [
  { moduleId: 'fusion_cell_mk3', name: 'Fusion Cell Mk3', category: 'generator', hp: 20, maxHp: 20, active: true, energyCost: -200, stats: { apRegen: 8, energyPerRound: 200 } },
  { moduleId: 'puls_laser_mk3', name: 'Puls-Laser Mk3', category: 'weapon_energy', hp: 80, maxHp: 80, active: true, energyCost: 26, stats: { atk: 28 } },
  { moduleId: 'schild_gen_mk2', name: 'Schild-Gen Mk2', category: 'shield', hp: 20, maxHp: 20, active: true, energyCost: 120, stats: { shield: 200, regen: 6 } },
  { moduleId: 'armor_plating_mk2', name: 'Armor Plating Mk2', category: 'armor', hp: 300, maxHp: 300, active: true, energyCost: 0, stats: { shieldBonus: 0.1 } },
];

const npcLevel3 = generateNpcCombatStats(3);

describe('initCombatV3', () => {
  it('creates valid initial state', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    expect(state.round).toBe(0);
    expect(state.maxRounds).toBe(10);
    expect(state.playerShield).toBe(200);
    expect(state.playerShieldRegen).toBe(6);
    expect(state.playerArmorHp).toBe(300);
    expect(state.playerEnergyBudget).toBe(200);
    expect(state.enemyShield).toBe(240);
    expect(state.enemyArmorHp).toBe(280);
  });
});

describe('validateEnergyBudget', () => {
  it('accepts within budget', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    const result = validateEnergyBudget(state, ['puls_laser_mk3', 'schild_gen_mk2']);
    expect(result.valid).toBe(true);
    expect(result.totalCost).toBe(146); // 26 + 120
  });
  it('rejects over budget', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    // If we had more modules that exceed 200...
    const overModules: CombatModule[] = [
      ...mockModules,
      { moduleId: 'ecm1', name: 'ECM', category: 'defense_ecm', hp: 40, maxHp: 40, active: true, energyCost: 60, stats: {} },
    ];
    const overState = initCombatV3(overModules, npcLevel3);
    const result = validateEnergyBudget(overState, ['puls_laser_mk3', 'schild_gen_mk2', 'ecm1']);
    expect(result.valid).toBe(false);
  });
});

describe('resolveRoundV3', () => {
  it('increments round and deals damage', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    const { newState, roundResult } = resolveRoundV3(state, {
      activeModules: ['puls_laser_mk3', 'schild_gen_mk2'],
      tactic: 'balanced',
    }, 12345);
    expect(newState.round).toBe(1);
    expect(roundResult.round).toBe(1);
    expect(roundResult.playerDamageDealt).toBeGreaterThanOrEqual(0);
  });

  it('assault tactic deals more damage than balanced', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    const assault = resolveRoundV3(state, { activeModules: ['puls_laser_mk3'], tactic: 'assault' }, 99999);
    const balanced = resolveRoundV3(state, { activeModules: ['puls_laser_mk3'], tactic: 'balanced' }, 99999);
    expect(assault.roundResult.playerDamageDealt).toBeGreaterThanOrEqual(balanced.roundResult.playerDamageDealt);
  });

  it('shield regenerates', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    state.playerShield = 100; // damaged
    const { newState } = resolveRoundV3(state, { activeModules: ['schild_gen_mk2'], tactic: 'balanced' }, 55555);
    // Shield should have regenerated by regen value (6) before damage
    // Can't test exact value due to damage, but should be >= 100 if no enemy hits
  });

  it('round 10 is a draw', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    state.round = 9;
    const { newState } = resolveRoundV3(state, { activeModules: ['puls_laser_mk3'], tactic: 'balanced' }, 11111);
    expect(newState.round).toBe(10);
    if (!newState.outcome || newState.outcome === 'draw') {
      // draw or victory if we killed them this round — both valid
      expect(['draw', 'victory', undefined]).toContain(newState.outcome);
    }
  });
});

describe('attemptFleeV3', () => {
  it('cannot flee round 0 or 1', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    state.round = 1;
    const result = attemptFleeV3(state, 12345);
    expect(result.success).toBe(false);
  });

  it('can attempt from round 2', () => {
    const state = initCombatV3(mockModules, npcLevel3);
    state.round = 2;
    const result = attemptFleeV3(state, 12345);
    // Result depends on seed — just verify it returns a valid structure
    expect(typeof result.success).toBe('boolean');
    expect(result.newState).toBeDefined();
  });
});
