export interface ModuleDefinition {
  id: string;
  name: string;
  category: string;
  tier: number;
  slot: string;
  costCredits: number;
  costOre: number;
  costGas: number;
  costCrystal: number;
  costArtefact: string; // e.g. "20 Engine Artefact" or "0"
  apCost: number;
  energyCost: number;
  hitpoints: number;
  stats: Record<string, number>;
  description: string;
  isFoundOnly: boolean;
  isUnique: boolean;
  prerequisiteModuleId?: string;
}

export const MODULE_DEFINITIONS: ModuleDefinition[] = [
  // ─── DRIVES ──────────────────────────────────────────────────────────────────
  {
    id: 'ion_drive_mk1',
    name: 'Ion Drive Mk1',
    category: 'drive',
    tier: 1,
    slot: 'engine',
    costCredits: 250,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 1,
    energyCost: 10,
    hitpoints: 20,
    stats: { jumpDistance: 32, rechargeRate: 4, fuelCapacity: 2000, fuelPerSector: 10, msPerSector: 200 },
    description: 'Einfacher Ionenantrieb der ersten Generation.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'ion_drive_mk2',
    name: 'Ion Drive Mk2',
    category: 'drive',
    tier: 2,
    slot: 'engine',
    costCredits: 750,
    costOre: 25,
    costGas: 40,
    costCrystal: 80,
    costArtefact: '0',
    apCost: 2,
    energyCost: 12,
    hitpoints: 20,
    stats: { jumpDistance: 48, rechargeRate: 6, fuelCapacity: 4000, fuelPerSector: 20, msPerSector: 160 },
    description: 'Verbesserter Ionenantrieb mit höherer Sprungweite.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'ion_drive_mk1',
  },
  {
    id: 'ion_drive_mk3',
    name: 'Ion Drive Mk3',
    category: 'drive',
    tier: 3,
    slot: 'engine',
    costCredits: 2500,
    costOre: 50,
    costGas: 80,
    costCrystal: 120,
    costArtefact: '0',
    apCost: 3,
    energyCost: 14,
    hitpoints: 20,
    stats: { jumpDistance: 64, rechargeRate: 8, fuelCapacity: 8000, fuelPerSector: 20, msPerSector: 120 },
    description: 'Hochleistungsionentriebwerk der dritten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'ion_drive_mk2',
  },
  {
    id: 'proto_am_drive',
    name: 'Proto AM Drive',
    category: 'drive',
    tier: 4,
    slot: 'engine',
    costCredits: 10000,
    costOre: 250,
    costGas: 200,
    costCrystal: 180,
    costArtefact: '10 Engine Artefact',
    apCost: 2,
    energyCost: 22,
    hitpoints: 15,
    stats: { jumpDistance: 100, rechargeRate: 6, fuelCapacity: 2000, fuelPerSector: 60, msPerSector: 80 },
    description: 'Prototyp eines Antimaterie-Antriebs mit enormer Geschwindigkeit.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'ion_drive_mk3',
  },
  {
    id: 'am_drive_mk1',
    name: 'AM Drive Mk1',
    category: 'drive',
    tier: 5,
    slot: 'engine',
    costCredits: 25000,
    costOre: 400,
    costGas: 225,
    costCrystal: 300,
    costArtefact: '20 Engine Artefact',
    apCost: 2,
    energyCost: 26,
    hitpoints: 40,
    stats: { jumpDistance: 150, rechargeRate: 12, fuelCapacity: 12000, fuelPerSector: 60, msPerSector: 200 },
    description: 'Antimaterie-Antrieb erster Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'proto_am_drive',
  },
  {
    id: 'am_drive_mk2',
    name: 'AM Drive Mk2',
    category: 'drive',
    tier: 6,
    slot: 'engine',
    costCredits: 50000,
    costOre: 600,
    costGas: 250,
    costCrystal: 400,
    costArtefact: '50 Engine Artefact',
    apCost: 1,
    energyCost: 28,
    hitpoints: 60,
    stats: { jumpDistance: 250, rechargeRate: 16, fuelCapacity: 20000, fuelPerSector: 120, msPerSector: 200 },
    description: 'Hochentwickelter Antimaterie-Antrieb mit enormer Sprungweite.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'am_drive_mk1',
  },
  {
    id: 'rift_drive',
    name: 'Rift-Drive',
    category: 'drive',
    tier: 5,
    slot: 'engine',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 4,
    energyCost: 34,
    hitpoints: 200,
    stats: { jumpDistance: 400, rechargeRate: 24, fuelCapacity: 2000, fuelPerSector: 10, msPerSector: 200 },
    description: 'Legendärer Riftantrieb — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },
  {
    id: 'void_drive',
    name: 'Void-Drive',
    category: 'drive',
    tier: 6,
    slot: 'engine',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 2,
    energyCost: 34,
    hitpoints: 200,
    stats: { jumpDistance: 1200, rechargeRate: 24, fuelCapacity: 2000, fuelPerSector: 10, msPerSector: 200 },
    description: 'Mythischer Void-Antrieb aus einer vergessenen Zivilisation.',
    isFoundOnly: true,
    isUnique: true,
  },

  // ─── GENERATORS ──────────────────────────────────────────────────────────────
  {
    id: 'fusion_cell_mk1',
    name: 'Fusion Cell Mk1',
    category: 'generator',
    tier: 1,
    slot: 'generator',
    costCredits: 250,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: -4,
    energyCost: -100,
    hitpoints: 20,
    stats: { apRegen: 4, energyPerRound: 100 },
    description: 'Standard-Fusionszelle. Vorinstalliert auf jedem Schiff.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'fusion_cell_mk2',
    name: 'Fusion Cell Mk2',
    category: 'generator',
    tier: 2,
    slot: 'generator',
    costCredits: 750,
    costOre: 25,
    costGas: 40,
    costCrystal: 80,
    costArtefact: '0',
    apCost: -6,
    energyCost: -150,
    hitpoints: 20,
    stats: { apRegen: 6, energyPerRound: 150 },
    description: 'Verbesserte Fusionszelle mit höherer Energieausbeute.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'fusion_cell_mk1',
  },
  {
    id: 'fusion_cell_mk3',
    name: 'Fusion Cell Mk3',
    category: 'generator',
    tier: 3,
    slot: 'generator',
    costCredits: 2500,
    costOre: 50,
    costGas: 80,
    costCrystal: 120,
    costArtefact: '0',
    apCost: -8,
    energyCost: -200,
    hitpoints: 20,
    stats: { apRegen: 8, energyPerRound: 200 },
    description: 'Hochleistungsfusionszelle der dritten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'fusion_cell_mk2',
  },
  {
    id: 'fusion_cell_mk4',
    name: 'Fusion Cell Mk4',
    category: 'generator',
    tier: 4,
    slot: 'generator',
    costCredits: 10000,
    costOre: 250,
    costGas: 200,
    costCrystal: 180,
    costArtefact: '10 Engine Artefact',
    apCost: -10,
    energyCost: -250,
    hitpoints: 40,
    stats: { apRegen: 10, energyPerRound: 250 },
    description: 'Erweiterte Fusionszelle mit enormer AP-Regeneration.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'fusion_cell_mk3',
  },
  {
    id: 'am_generator',
    name: 'AM Generator',
    category: 'generator',
    tier: 5,
    slot: 'generator',
    costCredits: 25000,
    costOre: 400,
    costGas: 225,
    costCrystal: 300,
    costArtefact: '20 Engine Artefact',
    apCost: -12,
    energyCost: -500,
    hitpoints: 60,
    stats: { apRegen: 12, energyPerRound: 500 },
    description: 'Antimaterie-Generator für maximale Energieversorgung.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'fusion_cell_mk4',
  },
  {
    id: 'am_generator_mk2',
    name: 'AM Generator Mk2',
    category: 'generator',
    tier: 6,
    slot: 'generator',
    costCredits: 50000,
    costOre: 600,
    costGas: 250,
    costCrystal: 400,
    costArtefact: '50 Engine Artefact',
    apCost: -14,
    energyCost: -750,
    hitpoints: 80,
    stats: { apRegen: 14, energyPerRound: 750 },
    description: 'Hochentwickelter Antimaterie-Generator der zweiten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'am_generator',
  },
  {
    id: 'string_generator',
    name: 'String Generator',
    category: 'generator',
    tier: 5,
    slot: 'generator',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: -20,
    energyCost: -1000,
    hitpoints: 200,
    stats: { apRegen: 20, energyPerRound: 1000 },
    description: 'Exotischer String-Generator aus uralter Technologie.',
    isFoundOnly: true,
    isUnique: true,
  },
  {
    id: 'void_generator',
    name: 'Void Generator',
    category: 'generator',
    tier: 6,
    slot: 'generator',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: -40,
    energyCost: -1500,
    hitpoints: 200,
    stats: { apRegen: 40, energyPerRound: 1500 },
    description: 'Legendärer Void-Generator mit unglaublicher Energiekapazität.',
    isFoundOnly: true,
    isUnique: true,
  },

  // ─── MINING ──────────────────────────────────────────────────────────────────
  {
    id: 'mining_laser_mk1',
    name: 'Mining Laser Mk1',
    category: 'mining',
    tier: 1,
    slot: 'mining',
    costCredits: 100,
    costOre: 10,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 4,
    energyCost: 10,
    hitpoints: 20,
    stats: { miningSpeed: 1 },
    description: 'Einfacher Mining-Laser für den Rohstoffabbau.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'mining_laser_mk2',
    name: 'Mining Laser Mk2',
    category: 'mining',
    tier: 2,
    slot: 'mining',
    costCredits: 300,
    costOre: 20,
    costGas: 0,
    costCrystal: 5,
    costArtefact: '0',
    apCost: 6,
    energyCost: 12,
    hitpoints: 20,
    stats: { miningSpeed: 4 },
    description: 'Verbesserter Mining-Laser mit höherer Abbaurate.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'mining_laser_mk1',
  },
  {
    id: 'mining_laser_mk3',
    name: 'Mining Laser Mk3',
    category: 'mining',
    tier: 3,
    slot: 'mining',
    costCredits: 700,
    costOre: 35,
    costGas: 0,
    costCrystal: 15,
    costArtefact: '0',
    apCost: 8,
    energyCost: 14,
    hitpoints: 20,
    stats: { miningSpeed: 10 },
    description: 'Hochleistungs-Mining-Laser der dritten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'mining_laser_mk2',
  },
  {
    id: 'mining_laser_mk4',
    name: 'Mining Laser Mk4',
    category: 'mining',
    tier: 4,
    slot: 'mining',
    costCredits: 1500,
    costOre: 60,
    costGas: 0,
    costCrystal: 30,
    costArtefact: '2 Mining Artefact',
    apCost: 10,
    energyCost: 22,
    hitpoints: 40,
    stats: { miningSpeed: 25 },
    description: 'Industrieller Mining-Laser der vierten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'mining_laser_mk3',
  },
  {
    id: 'mining_laser_mk5',
    name: 'Mining Laser Mk5',
    category: 'mining',
    tier: 5,
    slot: 'mining',
    costCredits: 4000,
    costOre: 100,
    costGas: 0,
    costCrystal: 60,
    costArtefact: '6 Mining Artefact',
    apCost: 12,
    energyCost: 26,
    hitpoints: 60,
    stats: { miningSpeed: 50 },
    description: 'Spitzen-Mining-Laser für maximalen Rohstoffabbau.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'mining_laser_mk4',
  },

  // ─── CARGO ───────────────────────────────────────────────────────────────────
  {
    id: 'cargo_bay_mk1',
    name: 'Cargo Bay Mk1',
    category: 'cargo',
    tier: 1,
    slot: 'cargo',
    costCredits: 80,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 4,
    energyCost: 0,
    hitpoints: 1,
    stats: { cargoCapacity: 25 },
    description: 'Einfacher Frachtraum für zusätzliche Ladekapazität.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'cargo_bay_mk2',
    name: 'Cargo Bay Mk2',
    category: 'cargo',
    tier: 2,
    slot: 'cargo',
    costCredits: 250,
    costOre: 15,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 6,
    energyCost: 0,
    hitpoints: 1,
    stats: { cargoCapacity: 50 },
    description: 'Erweiterter Frachtraum der zweiten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'cargo_bay_mk1',
  },
  {
    id: 'cargo_bay_mk3',
    name: 'Cargo Bay Mk3',
    category: 'cargo',
    tier: 3,
    slot: 'cargo',
    costCredits: 600,
    costOre: 30,
    costGas: 10,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 8,
    energyCost: 0,
    hitpoints: 1,
    stats: { cargoCapacity: 100 },
    description: 'Großer Frachtraum für intensive Handelsmissionen.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'cargo_bay_mk2',
  },
  {
    id: 'cargo_bay_mk4',
    name: 'Cargo Bay Mk4',
    category: 'cargo',
    tier: 4,
    slot: 'cargo',
    costCredits: 1500,
    costOre: 50,
    costGas: 20,
    costCrystal: 0,
    costArtefact: '2 Cargo Artefact',
    apCost: 10,
    energyCost: 0,
    hitpoints: 1,
    stats: { cargoCapacity: 175 },
    description: 'Industrieller Frachtraum mit Komprimierungstechnik.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'cargo_bay_mk3',
  },
  {
    id: 'cargo_bay_mk5',
    name: 'Cargo Bay Mk5',
    category: 'cargo',
    tier: 5,
    slot: 'cargo',
    costCredits: 4000,
    costOre: 100,
    costGas: 40,
    costCrystal: 0,
    costArtefact: '5 Cargo Artefact',
    apCost: 12,
    energyCost: 0,
    hitpoints: 1,
    stats: { cargoCapacity: 250 },
    description: 'Maximaler Frachtraum für Handelsgiganten.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'cargo_bay_mk4',
  },

  // ─── SCANNER ─────────────────────────────────────────────────────────────────
  {
    id: 'scanner_mk1',
    name: 'Scanner Mk1',
    category: 'scanner',
    tier: 1,
    slot: 'scanner',
    costCredits: 120,
    costOre: 0,
    costGas: 0,
    costCrystal: 5,
    costArtefact: '0',
    apCost: 4,
    energyCost: 10,
    hitpoints: 20,
    stats: { scanRange: 3 },
    description: 'Einfaches Scanner-System für Nahbereichsaufklärung.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'scanner_mk2',
    name: 'Scanner Mk2',
    category: 'scanner',
    tier: 2,
    slot: 'scanner',
    costCredits: 350,
    costOre: 0,
    costGas: 0,
    costCrystal: 15,
    costArtefact: '0',
    apCost: 6,
    energyCost: 12,
    hitpoints: 20,
    stats: { scanRange: 6 },
    description: 'Verbessertes Scanner-System mit doppelter Reichweite.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'scanner_mk1',
  },
  {
    id: 'scanner_mk3',
    name: 'Scanner Mk3',
    category: 'scanner',
    tier: 3,
    slot: 'scanner',
    costCredits: 900,
    costOre: 0,
    costGas: 10,
    costCrystal: 30,
    costArtefact: '0',
    apCost: 8,
    energyCost: 14,
    hitpoints: 20,
    stats: { scanRange: 9 },
    description: 'Erweitertes Langstrecken-Scanner-System.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'scanner_mk2',
  },
  {
    id: 'scanner_mk4',
    name: 'Scanner Mk4',
    category: 'scanner',
    tier: 4,
    slot: 'scanner',
    costCredits: 2000,
    costOre: 0,
    costGas: 20,
    costCrystal: 50,
    costArtefact: '2 Scanner Artefact',
    apCost: 10,
    energyCost: 22,
    hitpoints: 40,
    stats: { scanRange: 12 },
    description: 'Hochauflösendes Sensor-Array der vierten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'scanner_mk3',
  },
  {
    id: 'scanner_mk5',
    name: 'Scanner Mk5',
    category: 'scanner',
    tier: 5,
    slot: 'scanner',
    costCredits: 5000,
    costOre: 0,
    costGas: 40,
    costCrystal: 100,
    costArtefact: '6 Scanner Artefact',
    apCost: 12,
    energyCost: 26,
    hitpoints: 60,
    stats: { scanRange: 18 },
    description: 'Militärisches Weitbereichs-Scanner-System.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'scanner_mk4',
  },
  {
    id: 'quantum_scanner',
    name: 'Quantum Scanner',
    category: 'scanner',
    tier: 5,
    slot: 'scanner',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 24,
    energyCost: 48,
    hitpoints: 120,
    stats: { scanRange: 36 },
    description: 'Quantenbasiertes Scanner-System — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },

  // ─── REPAIR ──────────────────────────────────────────────────────────────────
  {
    id: 'repair_drone_mk1',
    name: 'Repair Drone Mk1',
    category: 'repair',
    tier: 1,
    slot: 'repair',
    costCredits: 200,
    costOre: 20,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 4,
    energyCost: 10,
    hitpoints: 20,
    stats: { repairRate: 2 },
    description: 'Einfache Reparaturdrohne für Feldwartung.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'repair_drone_mk2',
    name: 'Repair Drone Mk2',
    category: 'repair',
    tier: 2,
    slot: 'repair',
    costCredits: 500,
    costOre: 40,
    costGas: 0,
    costCrystal: 5,
    costArtefact: '0',
    apCost: 6,
    energyCost: 12,
    hitpoints: 20,
    stats: { repairRate: 4 },
    description: 'Verbesserte Reparaturdrohne mit höherer Reparaturrate.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'repair_drone_mk1',
  },
  {
    id: 'repair_drone_mk3',
    name: 'Repair Drone Mk3',
    category: 'repair',
    tier: 3,
    slot: 'repair',
    costCredits: 1200,
    costOre: 60,
    costGas: 0,
    costCrystal: 20,
    costArtefact: '0',
    apCost: 8,
    energyCost: 14,
    hitpoints: 20,
    stats: { repairRate: 8 },
    description: 'Hochleistungsreparaturdrohne der dritten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'repair_drone_mk2',
  },
  {
    id: 'repair_drone_mk4',
    name: 'Repair Drone Mk4',
    category: 'repair',
    tier: 4,
    slot: 'repair',
    costCredits: 2500,
    costOre: 90,
    costGas: 0,
    costCrystal: 40,
    costArtefact: '1 Repair Artefact',
    apCost: 10,
    energyCost: 22,
    hitpoints: 40,
    stats: { repairRate: 12 },
    description: 'Industrielle Reparaturdrohne für schwere Schäden.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'repair_drone_mk3',
  },
  {
    id: 'nano_bots_mk1',
    name: 'Nano Bots Mk1',
    category: 'repair',
    tier: 5,
    slot: 'repair',
    costCredits: 5000,
    costOre: 140,
    costGas: 0,
    costCrystal: 70,
    costArtefact: '2 Repair Artefact',
    apCost: 12,
    energyCost: 26,
    hitpoints: 60,
    stats: { repairRate: 16 },
    description: 'Nanobotensystem für schnelle Reparaturen auf molekularer Ebene.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'repair_drone_mk4',
  },
  {
    id: 'nano_bots_mk2',
    name: 'Nano Bots Mk2',
    category: 'repair',
    tier: 5,
    slot: 'repair',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 24,
    energyCost: 48,
    hitpoints: 120,
    stats: { repairRate: 24 },
    description: 'Hochentwickelte Nanoboten — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },

  // ─── ARMOR ───────────────────────────────────────────────────────────────────
  {
    id: 'armor_plating_mk1',
    name: 'Armor Plating Mk1',
    category: 'armor',
    tier: 1,
    slot: 'armor',
    costCredits: 100,
    costOre: 15,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 0,
    energyCost: 0,
    hitpoints: 200,
    stats: {},
    description: 'Einfache Panzerung für grundlegenden Schutz.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'armor_plating_mk2',
    name: 'Armor Plating Mk2',
    category: 'armor',
    tier: 2,
    slot: 'armor',
    costCredits: 300,
    costOre: 30,
    costGas: 0,
    costCrystal: 10,
    costArtefact: '0',
    apCost: 0,
    energyCost: 0,
    hitpoints: 300,
    stats: { shieldBonus: 0.1 },
    description: 'Verstärkte Panzerung mit Schildverstärkung.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'armor_plating_mk1',
  },
  {
    id: 'armor_plating_mk3',
    name: 'Armor Plating Mk3',
    category: 'armor',
    tier: 3,
    slot: 'armor',
    costCredits: 800,
    costOre: 250,
    costGas: 0,
    costCrystal: 25,
    costArtefact: '0',
    apCost: 0,
    energyCost: 0,
    hitpoints: 400,
    stats: {},
    description: 'Schwere Panzerplatten der dritten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'armor_plating_mk2',
  },
  {
    id: 'armor_plating_mk4',
    name: 'Armor Plating Mk4',
    category: 'armor',
    tier: 4,
    slot: 'armor',
    costCredits: 1800,
    costOre: 400,
    costGas: 0,
    costCrystal: 40,
    costArtefact: '2 Armor Artefact',
    apCost: 0,
    energyCost: 0,
    hitpoints: 600,
    stats: { shieldBonus: 0.2 },
    description: 'Verbundpanzerung mit Schildsynergie.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'armor_plating_mk3',
  },
  {
    id: 'armor_plating_mk5',
    name: 'Armor Plating Mk5',
    category: 'armor',
    tier: 5,
    slot: 'armor',
    costCredits: 4500,
    costOre: 600,
    costGas: 0,
    costCrystal: 80,
    costArtefact: '6 Armor Artefact',
    apCost: 0,
    energyCost: 0,
    hitpoints: 800,
    stats: { shieldBonus: 0.2 },
    description: 'Militärische Hochleistungspanzerung.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'armor_plating_mk4',
  },
  {
    id: 'nano_armor',
    name: 'Nano Armor',
    category: 'armor',
    tier: 3,
    slot: 'armor',
    costCredits: 1800,
    costOre: 1200,
    costGas: 0,
    costCrystal: 50,
    costArtefact: '20 Armor Artefact',
    apCost: 0,
    energyCost: 0,
    hitpoints: 1000,
    stats: { damageReduction: 0.35 },
    description: 'Nanomaterial-Rüstung mit einzigartiger Schadensreduktion.',
    isFoundOnly: false,
    isUnique: true,
  },
  {
    id: 'living_hull',
    name: 'Living Hull',
    category: 'armor',
    tier: 4,
    slot: 'armor',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: -4,
    energyCost: 0,
    hitpoints: 1500,
    stats: {},
    description: 'Lebende Rumpfhülle aus fremder Biotechnologie — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },
  {
    id: 'salvage_skin',
    name: 'Salvage Skin',
    category: 'armor',
    tier: 3,
    slot: 'armor',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 0,
    energyCost: 0,
    hitpoints: 2500,
    stats: {},
    description: 'Massiver Bergungsrumpf aus fremden Materialien — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },

  // ─── SHIELDS ─────────────────────────────────────────────────────────────────
  {
    id: 'schild_gen_mk1',
    name: 'Schild-Gen Mk1',
    category: 'shield',
    tier: 1,
    slot: 'shield',
    costCredits: 200,
    costOre: 0,
    costGas: 40,
    costCrystal: 15,
    costArtefact: '0',
    apCost: 4,
    energyCost: 60,
    hitpoints: 20,
    stats: { shield: 100, regen: 3 },
    description: 'Einfacher Schildgenerator für grundlegenden Energieschutz.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'schild_gen_mk2',
    name: 'Schild-Gen Mk2',
    category: 'shield',
    tier: 2,
    slot: 'shield',
    costCredits: 600,
    costOre: 0,
    costGas: 80,
    costCrystal: 35,
    costArtefact: '0',
    apCost: 6,
    energyCost: 120,
    hitpoints: 20,
    stats: { shield: 200, regen: 6 },
    description: 'Verbesserter Schildgenerator mit höherer Kapazität.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'schild_gen_mk1',
  },
  {
    id: 'schild_gen_mk3',
    name: 'Schild-Gen Mk3',
    category: 'shield',
    tier: 3,
    slot: 'shield',
    costCredits: 1500,
    costOre: 0,
    costGas: 120,
    costCrystal: 270,
    costArtefact: '10 Shield Artefact',
    apCost: 8,
    energyCost: 180,
    hitpoints: 20,
    stats: { shield: 400, regen: 12 },
    description: 'Hochleistungsschildgenerator der dritten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'schild_gen_mk2',
  },
  {
    id: 'am_shield_mk1',
    name: 'AM Shield Mk1',
    category: 'shield',
    tier: 4,
    slot: 'shield',
    costCredits: 25000,
    costOre: 0,
    costGas: 160,
    costCrystal: 380,
    costArtefact: '20 Shield Artefact',
    apCost: 10,
    energyCost: 200,
    hitpoints: 40,
    stats: { shield: 800, regen: 12, damageReduction: 0.1 },
    description: 'Antimaterie-Schildgenerator mit Schadensreduktion.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'schild_gen_mk3',
  },
  {
    id: 'am_shield_mk2',
    name: 'AM Shield Mk2',
    category: 'shield',
    tier: 5,
    slot: 'shield',
    costCredits: 45000,
    costOre: 0,
    costGas: 260,
    costCrystal: 640,
    costArtefact: '40 Shield Artefact',
    apCost: 8,
    energyCost: 250,
    hitpoints: 60,
    stats: { shield: 1000, regen: 12, damageReduction: 0.1 },
    description: 'Hochentwickelter Antimaterie-Schildgenerator.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'am_shield_mk1',
  },

  // ─── WEAPONS — ENERGY ────────────────────────────────────────────────────────
  {
    id: 'puls_laser_mk1',
    name: 'Puls-Laser Mk1',
    category: 'weapon_energy',
    tier: 1,
    slot: 'weapon',
    costCredits: 150,
    costOre: 0,
    costGas: 0,
    costCrystal: 10,
    costArtefact: '0',
    apCost: 5,
    energyCost: 14,
    hitpoints: 40,
    stats: { atk: 8 },
    description: 'Einfacher Pulslaser für Anfangsgefechte.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'puls_laser_mk2',
    name: 'Puls-Laser Mk2',
    category: 'weapon_energy',
    tier: 2,
    slot: 'weapon',
    costCredits: 450,
    costOre: 0,
    costGas: 10,
    costCrystal: 25,
    costArtefact: '0',
    apCost: 5,
    energyCost: 22,
    hitpoints: 60,
    stats: { atk: 16 },
    description: 'Verbesserter Pulslaser mit doppelter Angriffspower.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'puls_laser_mk1',
  },
  {
    id: 'puls_laser_mk3',
    name: 'Puls-Laser Mk3',
    category: 'weapon_energy',
    tier: 3,
    slot: 'weapon',
    costCredits: 1200,
    costOre: 0,
    costGas: 20,
    costCrystal: 50,
    costArtefact: '0',
    apCost: 5,
    energyCost: 26,
    hitpoints: 80,
    stats: { atk: 28 },
    description: 'Hochleistungspulslaser der dritten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'puls_laser_mk2',
  },
  {
    id: 'puls_laser_mk4',
    name: 'Puls-Laser Mk4',
    category: 'weapon_energy',
    tier: 4,
    slot: 'weapon',
    costCredits: 2500,
    costOre: 0,
    costGas: 50,
    costCrystal: 80,
    costArtefact: '2 Weapon Artefact',
    apCost: 5,
    energyCost: 48,
    hitpoints: 50,
    stats: { atk: 45 },
    description: 'Militärischer Hochleistungslaser der vierten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'puls_laser_mk3',
  },
  {
    id: 'puls_laser_mk5',
    name: 'Puls-Laser Mk5',
    category: 'weapon_energy',
    tier: 5,
    slot: 'weapon',
    costCredits: 6000,
    costOre: 0,
    costGas: 100,
    costCrystal: 150,
    costArtefact: '5 Weapon Artefact',
    apCost: 5,
    energyCost: 60,
    hitpoints: 80,
    stats: { atk: 70 },
    description: 'Spitzenpulslaser mit maximaler Zerstörungskapazität.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'puls_laser_mk4',
  },
  {
    id: 'emp_emitter',
    name: 'EMP-Emitter',
    category: 'weapon_energy',
    tier: 2,
    slot: 'weapon',
    costCredits: 500,
    costOre: 0,
    costGas: 20,
    costCrystal: 20,
    costArtefact: '0',
    apCost: 5,
    energyCost: 40,
    hitpoints: 80,
    stats: { atk: 0, disabling: 1 },
    description: 'EMP-Emitter zur Deaktivierung feindlicher Systeme.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'ancient_lance',
    name: 'Ancient Lance',
    category: 'weapon_energy',
    tier: 5,
    slot: 'weapon',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 5,
    energyCost: 60,
    hitpoints: 40,
    stats: { atk: 45, piercing: 0.4 },
    description: 'Uralte Energielanze mit starker Durchdringungskraft — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },
  {
    id: 'void_ripper',
    name: 'Void Ripper',
    category: 'weapon_energy',
    tier: 4,
    slot: 'weapon',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 5,
    energyCost: 80,
    hitpoints: 60,
    stats: { atk: 35, recoilDamage: 0.1 },
    description: 'Verderbliche Raumverzerrungswaffe mit Rückstoßschaden — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },
  {
    id: 'leech_cannon',
    name: 'Leech Cannon',
    category: 'weapon_energy',
    tier: 3,
    slot: 'weapon',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 5,
    energyCost: 50,
    hitpoints: 80,
    stats: { atk: 20, bypassShield: 1 },
    description: 'Energiesauger-Kanone die Schilde ignoriert — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },
  {
    id: 'scrambler',
    name: 'Scrambler',
    category: 'weapon_energy',
    tier: 2,
    slot: 'weapon',
    costCredits: 0,
    costOre: 0,
    costGas: 0,
    costCrystal: 0,
    costArtefact: '0',
    apCost: 5,
    energyCost: 20,
    hitpoints: 120,
    stats: { atk: 5, disableSpecial: 1 },
    description: 'Störsender zur Deaktivierung von Spezialfähigkeiten — nur durch Erkundung zu finden.',
    isFoundOnly: true,
    isUnique: true,
  },

  // ─── WEAPONS — KINETIC ───────────────────────────────────────────────────────
  {
    id: 'rail_kanone_mk1',
    name: 'Rail-Kanone Mk1',
    category: 'weapon_kinetic',
    tier: 1,
    slot: 'weapon',
    costCredits: 300,
    costOre: 30,
    costGas: 0,
    costCrystal: 15,
    costArtefact: '0',
    apCost: 5,
    energyCost: 14,
    hitpoints: 40,
    stats: { atk: 12, piercing: 0.3 },
    description: 'Kinetische Railgun mit Panzerbrecherfähigkeit.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'rail_kanone_mk2',
    name: 'Rail-Kanone Mk2',
    category: 'weapon_kinetic',
    tier: 2,
    slot: 'weapon',
    costCredits: 900,
    costOre: 60,
    costGas: 0,
    costCrystal: 30,
    costArtefact: '0',
    apCost: 5,
    energyCost: 22,
    hitpoints: 60,
    stats: { atk: 22, piercing: 0.5 },
    description: 'Verbesserte Railgun mit höherer Durchschlagskraft.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'rail_kanone_mk1',
  },
  {
    id: 'rail_kanone_mk3',
    name: 'Rail-Kanone Mk3',
    category: 'weapon_kinetic',
    tier: 3,
    slot: 'weapon',
    costCredits: 1200,
    costOre: 60,
    costGas: 0,
    costCrystal: 20,
    costArtefact: '1 Weapon Artefact',
    apCost: 5,
    energyCost: 26,
    hitpoints: 80,
    stats: { atk: 35, piercing: 0.65 },
    description: 'Hochleistungs-Railgun mit extremer Panzerdurchdringung.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'rail_kanone_mk2',
  },

  // ─── WEAPONS — MISSILE ───────────────────────────────────────────────────────
  {
    id: 'raketen_pod_mk1',
    name: 'Raketen-Pod Mk1',
    category: 'weapon_missile',
    tier: 1,
    slot: 'weapon',
    costCredits: 250,
    costOre: 20,
    costGas: 0,
    costCrystal: 5,
    costArtefact: '0',
    apCost: 5,
    energyCost: 10,
    hitpoints: 40,
    stats: { atk: 18 },
    description: 'Einfacher Raketenwerfer für Flächen- und Einzelzielangriffe.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'raketen_pod_mk2',
    name: 'Raketen-Pod Mk2',
    category: 'weapon_missile',
    tier: 2,
    slot: 'weapon',
    costCredits: 750,
    costOre: 40,
    costGas: 0,
    costCrystal: 15,
    costArtefact: '0',
    apCost: 5,
    energyCost: 11,
    hitpoints: 60,
    stats: { atk: 30 },
    description: 'Verbesserter Raketenwerfer mit größerem Magazin.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'raketen_pod_mk1',
  },
  {
    id: 'raketen_pod_mk3',
    name: 'Raketen-Pod Mk3',
    category: 'weapon_missile',
    tier: 3,
    slot: 'weapon',
    costCredits: 1000,
    costOre: 40,
    costGas: 20,
    costCrystal: 0,
    costArtefact: '1 Weapon Artefact',
    apCost: 5,
    energyCost: 20,
    hitpoints: 120,
    stats: { atk: 45 },
    description: 'Hochleistungsraketenwerfer mit schwerer Sprengstoffladung.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'raketen_pod_mk2',
  },

  // ─── DEFENSE — POINT DEFENSE ─────────────────────────────────────────────────
  {
    id: 'punkt_verteidigung_mk2',
    name: 'Punkt-Verteidigung Mk2',
    category: 'defense',
    tier: 2,
    slot: 'defense',
    costCredits: 450,
    costOre: 250,
    costGas: 15,
    costCrystal: 250,
    costArtefact: '10 Defense Artefact',
    apCost: -8,
    energyCost: 40,
    hitpoints: 40,
    stats: { interceptChance: 0.3 },
    description: 'Punktverteidigungssystem zur Abwehr von Raketenangriffen.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'punkt_verteidigung_mk3',
    name: 'Punkt-Verteidigung Mk3',
    category: 'defense',
    tier: 3,
    slot: 'defense',
    costCredits: 1200,
    costOre: 400,
    costGas: 15,
    costCrystal: 400,
    costArtefact: '20 Defense Artefact',
    apCost: -10,
    energyCost: 60,
    hitpoints: 60,
    stats: { interceptChance: 0.3 },
    description: 'Erweitertes Punktverteidigungssystem der dritten Generation.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'punkt_verteidigung_mk2',
  },
  {
    id: 'punkt_verteidigung_mk4',
    name: 'Punkt-Verteidigung Mk4',
    category: 'defense',
    tier: 4,
    slot: 'defense',
    costCredits: 2500,
    costOre: 600,
    costGas: 15,
    costCrystal: 600,
    costArtefact: '40 Defense Artefact',
    apCost: -12,
    energyCost: 80,
    hitpoints: 80,
    stats: { interceptChance: 0.3 },
    description: 'Militärisches Hochleistungspunktverteidigungssystem.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'punkt_verteidigung_mk3',
  },

  // ─── DEFENSE — ECM ───────────────────────────────────────────────────────────
  {
    id: 'ecm_suite_1',
    name: 'ECM Suite 1',
    category: 'defense',
    tier: 2,
    slot: 'defense',
    costCredits: 450,
    costOre: 250,
    costGas: 15,
    costCrystal: 250,
    costArtefact: '10 Defense Artefact',
    apCost: -8,
    energyCost: 40,
    hitpoints: 40,
    stats: { accuracyReduction: 0.15 },
    description: 'Elektronisches Gegenmanahmensystem zur Treffervermeidung.',
    isFoundOnly: false,
    isUnique: false,
  },
  {
    id: 'ecm_suite_2',
    name: 'ECM Suite 2',
    category: 'defense',
    tier: 3,
    slot: 'defense',
    costCredits: 1200,
    costOre: 400,
    costGas: 15,
    costCrystal: 400,
    costArtefact: '20 Defense Artefact',
    apCost: -10,
    energyCost: 60,
    hitpoints: 60,
    stats: { accuracyReduction: 0.15 },
    description: 'Erweitertes ECM-System der zweiten Stufe.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'ecm_suite_1',
  },
  {
    id: 'ecm_suite_3',
    name: 'ECM Suite 3',
    category: 'defense',
    tier: 4,
    slot: 'defense',
    costCredits: 2500,
    costOre: 600,
    costGas: 15,
    costCrystal: 600,
    costArtefact: '40 Defense Artefact',
    apCost: -12,
    energyCost: 80,
    hitpoints: 80,
    stats: { accuracyReduction: 0.15 },
    description: 'Militärisches Hochleistungs-ECM-System.',
    isFoundOnly: false,
    isUnique: false,
    prerequisiteModuleId: 'ecm_suite_2',
  },
];

/** Keyed lookup map for MODULE_DEFINITIONS by module id */
export const MODULE_MAP = new Map<string, ModuleDefinition>(
  MODULE_DEFINITIONS.map((m) => [m.id, m]),
);
