import { vi } from 'vitest';
import { useStore } from '../state/store';
import type { StoreState } from '../state/store';
import type { APState, SectorData, CargoState, ResearchState } from '@void-sector/shared';

const defaultAP: APState = {
  current: 100,
  max: 100,
  lastTick: Date.now(),
  regenPerSecond: 0.5,
};

const defaultSector: SectorData = {
  x: 0,
  y: 0,
  type: 'empty',
  seed: 42,
  discoveredBy: null,
  discoveredAt: null,
  metadata: {},
  environment: 'empty' as const,
  contents: [],
};

const defaultCargo: CargoState = {
  ore: 0,
  gas: 0,
  crystal: 0,
  slates: 0,
  artefact: 0,
  artefact_drive: 0,
  artefact_cargo: 0,
  artefact_scanner: 0,
  artefact_armor: 0,
  artefact_weapon: 0,
  artefact_shield: 0,
  artefact_defense: 0,
  artefact_special: 0,
  artefact_mining: 0,
};

export function mockStoreState(overrides: Partial<StoreState> = {}) {
  const state: Partial<StoreState> = {
    token: 'test-token',
    playerId: 'test-id',
    username: 'TestPilot',
    position: { x: 0, y: 0 },
    visitedTrail: [],
    ap: defaultAP,
    fuel: { current: 100, max: 100 },
    ship: null,
    currentSector: defaultSector,
    players: {},
    discoveries: { '0:0': defaultSector },
    log: [],
    mining: null,
    cargo: defaultCargo,
    activeMonitor: 'NAV-COM',
    alerts: {},
    selectedSector: null,
    baseStructures: [],
    credits: 0,
    storage: { ore: 0, gas: 0, crystal: 0, artefact: 0 },
    tradeOrders: [],
    myOrders: [],
    mySlates: [],
    faction: null,
    factionMembers: [],
    factionInvites: [],
    activeQuests: [],
    reputations: [],
    playerUpgrades: [],
    activeBattle: null,
    lastBattleResult: null,
    activeCombatV2: null,
    stationDefenses: [],
    stationCombatEvent: null,
    scanEvents: [],
    jumpGateInfo: null,
    rescuedSurvivors: [],
    distressCalls: [],
    factionUpgrades: [],
    tradeRoutes: [],
    bookmarks: [],
    autopilot: null,
    navTarget: null,
    autopilotStatus: null,
    discoveryTimestamps: {},
    shipList: [],
    moduleInventory: [],
    baseName: '',
    homeBase: { x: 0, y: 0 },
    research: {
      unlockedModules: [],
      blueprints: [],
      activeResearch: null,
      activeResearch2: null,
      wissen: 0,
      wissenRate: 0,
    },
    pendingBlueprint: null,
    npcStationData: null,
    factoryState: null,
    kontorOrders: [],
    knownQuadrants: [],
    currentQuadrant: null,
    firstContactEvent: null,
    hyperdriveState: null,
    autoRefuelConfig: { enabled: false, maxPricePerUnit: 10 },
    selectedTechModule: null,
    selectedBaseStructure: null,
    selectedCargoItem: null,
    selectedQuest: null,
    setSelectedTechModule: vi.fn(),
    setSelectedBaseStructure: vi.fn(),
    setSelectedCargoItem: vi.fn(),
    setSelectedQuest: vi.fn(),
    setStoryProgress: vi.fn(),
    setActiveCommunityQuest: vi.fn(),
    setHumanityReps: vi.fn(),
    setKontorOrders: vi.fn(),
    setKnownQuadrants: vi.fn(),
    setCurrentQuadrant: vi.fn(),
    setFirstContactEvent: vi.fn(),
    setHyperdriveState: vi.fn(),
    setAutoRefuelConfig: vi.fn(),
    setResearch: vi.fn(),
    setFactoryState: vi.fn(),
    setNpcStationData: vi.fn(),
    setPendingBlueprint: vi.fn(),
    activeTip: null,
    seenTips: new Set<string>(),
    showTip: vi.fn(),
    dismissTip: vi.fn(),
    hasSeenTip: vi.fn(),
    onboardingStep: null,
    advanceOnboarding: vi.fn(),
    skipOnboarding: vi.fn(),
    compendiumOpen: false,
    compendiumArticleId: null,
    compendiumSearch: '',
    openCompendium: vi.fn(),
    closeCompendium: vi.fn(),
    setCompendiumArticle: vi.fn(),
    setCompendiumSearch: vi.fn(),
    showArticlePopup: vi.fn(),
    alienReputations: {},
    humanityReps: {},
    storyProgress: null,
    activeCommunityQuest: null,
    alienCredits: 0,
    chatMessages: [],
    recentContacts: [],
    addRecentContact: vi.fn(),
    isGuest: false,
    autoFollow: false,
    monitorPower: {},
    monitorChromeVisible: {},
    monitorModes: {},
    moreOverlayOpen: false,
    setMoreOverlayOpen: vi.fn(),
    setMonitorPower: vi.fn(),
    setMonitorChromeVisible: vi.fn(),
    setMonitorMode: vi.fn(),
    setAlert: vi.fn(),
    clearAlert: vi.fn(),
    setSelectedSector: vi.fn(),
    setMySlates: vi.fn(),
    setFaction: vi.fn(),
    setFactionMembers: vi.fn(),
    setFactionInvites: vi.fn(),
    setActiveQuests: vi.fn(),
    setReputations: vi.fn(),
    setPlayerUpgrades: vi.fn(),
    setActiveBattle: vi.fn(),
    setLastBattleResult: vi.fn(),
    setActiveCombatV2: vi.fn(),
    setStationDefenses: vi.fn(),
    setStationCombatEvent: vi.fn(),
    setScanEvents: vi.fn(),
    addScanEvent: vi.fn(),
    setJumpGateInfo: vi.fn(),
    setRescuedSurvivors: vi.fn(),
    addDistressCall: vi.fn(),
    removeDistressCall: vi.fn(),
    setFactionUpgrades: vi.fn(),
    setTradeRoutes: vi.fn(),
    setBookmarks: vi.fn(),
    setAutopilot: vi.fn(),
    setNavTarget: vi.fn(),
    setAutopilotStatus: vi.fn(),
    setDiscoveryTimestamps: vi.fn(),
    setAutoFollow: vi.fn(),
    shipMoveAnimation: null,
    startShipMoveAnimation: vi.fn(),
    clearShipMoveAnimation: vi.fn(),
    screen: 'game' as const,
    theme: 'amber' as const,
    jumpPending: false,
    activeProgram: 'NAV-COM',
    setActiveProgram: vi.fn(),
    breadcrumbStack: [],
    pushBreadcrumb: vi.fn(),
    popBreadcrumb: vi.fn(),
    clearBreadcrumbs: vi.fn(),
    contextMenu: null,
    openContextMenu: vi.fn(),
    closeContextMenu: vi.fn(),
    stationTerminalOpen: false,
    openStationTerminal: vi.fn(),
    closeStationTerminal: vi.fn(),
    directChatRecipient: null,
    setDirectChatRecipient: vi.fn(),
    playerStats: {
      sectorsScanned: 0,
      quadrantsVisited: [],
      quadrantsFirstDiscovered: 0,
      stationsVisited: [],
      playersEncountered: 0,
    },
    incrementStat: vi.fn(),
    addToStatSet: vi.fn(),
    chatChannel: 'quadrant' as const,
    setChatChannel: vi.fn(),
    zoomLevel: 2,
    setZoomLevel: vi.fn(),
    panOffset: { x: 0, y: 0 },
    setPanOffset: vi.fn(),
    brightness: 1.0,
    setBrightness: vi.fn(),
    colorProfile: 'Amber Classic',
    setColorProfile: vi.fn(),
    scanPending: false,
    quadrantControls: [],
    npcFleets: [],
    warTicker: [],
    setQuadrantControls: vi.fn(),
    setNpcFleets: vi.fn(),
    addWarTickerEvent: vi.fn(),
    inventory: [],
    setInventory: vi.fn(),
    trackedQuests: [],
    setTrackedQuests: vi.fn(),
    ...overrides,
  };
  useStore.setState(state as StoreState);
}
