import { vi } from 'vitest';
import { useStore } from '../state/store';
import type { StoreState } from '../state/store';
import type { APState, SectorData, CargoState, ResearchState } from '@void-sector/shared';

const defaultAP: APState = {
  current: 100,
  max: 100,
  lastTick: Date.now(),
  regenPerSecond: 0.5,
};

const defaultSector: SectorData = {
  x: 0,
  y: 0,
  type: 'empty',
  seed: 42,
  discoveredBy: null,
  discoveredAt: null,
  metadata: {},
  environment: 'empty' as const,
  contents: [],
};

const defaultCargo: CargoState = { ore: 0, gas: 0, crystal: 0, slates: 0, artefact: 0 };

export function mockStoreState(overrides: Partial<StoreState> = {}) {
  const state: Partial<StoreState> = {
    token: 'test-token',
    playerId: 'test-id',
    username: 'TestPilot',
    position: { x: 0, y: 0 },
    ap: defaultAP,
    fuel: { current: 100, max: 100 },
    ship: null,
    currentSector: defaultSector,
    players: {},
    discoveries: { '0:0': defaultSector },
    log: [],
    mining: null,
    cargo: defaultCargo,
    activeMonitor: 'NAV-COM',
    alerts: {},
    selectedSector: null,
    baseStructures: [],
    credits: 0,
    storage: { ore: 0, gas: 0, crystal: 0, artefact: 0 },
    tradeOrders: [],
    myOrders: [],
    mySlates: [],
    faction: null,
    factionMembers: [],
    factionInvites: [],
    activeQuests: [],
    reputations: [],
    playerUpgrades: [],
    activeBattle: null,
    lastBattleResult: null,
    activeCombatV2: null,
    stationDefenses: [],
    stationCombatEvent: null,
    scanEvents: [],
    jumpGateInfo: null,
    rescuedSurvivors: [],
    distressCalls: [],
    factionUpgrades: [],
    tradeRoutes: [],
    bookmarks: [],
    autopilot: null,
    navTarget: null,
    autopilotStatus: null,
    discoveryTimestamps: {},
    shipList: [],
    moduleInventory: [],
    baseName: '',
    homeBase: { x: 0, y: 0 },
    research: { unlockedModules: [], blueprints: [], activeResearch: null },
    pendingBlueprint: null,
    npcStationData: null,
    factoryState: null,
    kontorOrders: [],
    knownQuadrants: [],
    currentQuadrant: null,
    firstContactEvent: null,
    hyperdriveState: null,
    autoRefuelConfig: { enabled: false, maxPricePerUnit: 10 },
    setKontorOrders: vi.fn(),
    setKnownQuadrants: vi.fn(),
    setCurrentQuadrant: vi.fn(),
    setFirstContactEvent: vi.fn(),
    setHyperdriveState: vi.fn(),
    setAutoRefuelConfig: vi.fn(),
    setResearch: vi.fn(),
    setFactoryState: vi.fn(),
    setNpcStationData: vi.fn(),
    setPendingBlueprint: vi.fn(),
    activeTip: null,
    seenTips: new Set<string>(),
    showTip: vi.fn(),
    dismissTip: vi.fn(),
    hasSeenTip: vi.fn(),
    alienCredits: 0,
    chatMessages: [],
    recentContacts: [],
    addRecentContact: vi.fn(),
    isGuest: false,
    sidebarSlots: ['SHIP-SYS', 'COMMS'] as [string, string],
    leftSidebarSlots: ['LOG', 'SHIP-SYS'] as [string, string],
    mainMonitorMode: 'split' as 'split' | string,
    autoFollow: false,
    monitorPower: {},
    monitorChromeVisible: {},
    monitorModes: {},
    setMonitorPower: vi.fn(),
    setMonitorChromeVisible: vi.fn(),
    setMonitorMode: vi.fn(),
    setAlert: vi.fn(),
    clearAlert: vi.fn(),
    setSelectedSector: vi.fn(),
    setLeftSidebarSlot: vi.fn(),
    setMainMonitorMode: vi.fn(),
    setMySlates: vi.fn(),
    setFaction: vi.fn(),
    setFactionMembers: vi.fn(),
    setFactionInvites: vi.fn(),
    setActiveQuests: vi.fn(),
    setReputations: vi.fn(),
    setPlayerUpgrades: vi.fn(),
    setActiveBattle: vi.fn(),
    setLastBattleResult: vi.fn(),
    setActiveCombatV2: vi.fn(),
    setStationDefenses: vi.fn(),
    setStationCombatEvent: vi.fn(),
    setScanEvents: vi.fn(),
    addScanEvent: vi.fn(),
    setJumpGateInfo: vi.fn(),
    setRescuedSurvivors: vi.fn(),
    addDistressCall: vi.fn(),
    removeDistressCall: vi.fn(),
    setFactionUpgrades: vi.fn(),
    setTradeRoutes: vi.fn(),
    setBookmarks: vi.fn(),
    setAutopilot: vi.fn(),
    setNavTarget: vi.fn(),
    setAutopilotStatus: vi.fn(),
    setDiscoveryTimestamps: vi.fn(),
    setAutoFollow: vi.fn(),
    screen: 'game' as const,
    theme: 'amber' as const,
    jumpPending: false,
    ...overrides,
  };
  useStore.setState(state as StoreState);
}
